Add required step to Creating a Pool docs.
Without this TS config setting, ts-node will throw an error: 

`Cannot find module '@uniswap/v3-core/artifacts/contracts/interfaces/IUniswapV3Pool.sol/IUniswapV3Pool.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.`

Adding in this tsconfig setup fixes the issue.